import { MasterData } from '../models/MasterData';

export const seedMasterData = async () => {
  try {
    // Check if master data already exists
    const existingData = await MasterData.countDocuments();
    if (existingData > 0) {
      console.log('📋 Master data already exists, skipping seed');
      return;
    }

    console.log('🌱 Seeding master data...');

    const masterDataItems = [
      // Organization Types
      {
        category: 'organizationType',
        key: 'government',
        value: 'Government',
        description: 'Government organization or department',
        displayOrder: 1,
        isActive: true,
      },
      {
        category: 'organizationType',
        key: 'ngo',
        value: 'NGO',
        description: 'Non-governmental organization',
        displayOrder: 2,
        isActive: true,
      },
      {
        category: 'organizationType',
        key: 'private',
        value: 'Private',
        description: 'Private sector organization',
        displayOrder: 3,
        isActive: true,
      },
      {
        category: 'organizationType',
        key: 'partner',
        value: 'Partner',
        description: 'Partner organization',
        displayOrder: 4,
        isActive: true,
      },

      // Industries
      {
        category: 'industry',
        key: 'technology',
        value: 'Technology',
        description: 'Technology and IT services',
        displayOrder: 1,
        isActive: true,
      },
      {
        category: 'industry',
        key: 'manufacturing',
        value: 'Manufacturing',
        description: 'Manufacturing and production',
        displayOrder: 2,
        isActive: true,
      },
      {
        category: 'industry',
        key: 'healthcare',
        value: 'Healthcare',
        description: 'Healthcare and medical services',
        displayOrder: 3,
        isActive: true,
      },
      {
        category: 'industry',
        key: 'finance',
        value: 'Finance',
        description: 'Financial services and banking',
        displayOrder: 4,
        isActive: true,
      },
      {
        category: 'industry',
        key: 'education',
        value: 'Education',
        description: 'Education and training services',
        displayOrder: 5,
        isActive: true,
      },
      {
        category: 'industry',
        key: 'retail',
        value: 'Retail',
        description: 'Retail and e-commerce',
        displayOrder: 6,
        isActive: true,
      },
      {
        category: 'industry',
        key: 'telecom',
        value: 'Telecommunications',
        description: 'Telecommunications services',
        displayOrder: 7,
        isActive: true,
      },
      {
        category: 'industry',
        key: 'other',
        value: 'Other',
        description: 'Other industries',
        displayOrder: 99,
        isActive: true,
      },

      // Countries
      {
        category: 'country',
        key: 'india',
        value: 'India',
        description: 'Republic of India',
        displayOrder: 1,
        isActive: true,
        metadata: { code: 'IN', dialCode: '+91' },
      },
      {
        category: 'country',
        key: 'usa',
        value: 'United States',
        description: 'United States of America',
        displayOrder: 2,
        isActive: true,
        metadata: { code: 'US', dialCode: '+1' },
      },
      {
        category: 'country',
        key: 'uk',
        value: 'United Kingdom',
        description: 'United Kingdom',
        displayOrder: 3,
        isActive: true,
        metadata: { code: 'GB', dialCode: '+44' },
      },
      {
        category: 'country',
        key: 'canada',
        value: 'Canada',
        description: 'Canada',
        displayOrder: 4,
        isActive: true,
        metadata: { code: 'CA', dialCode: '+1' },
      },
      {
        category: 'country',
        key: 'australia',
        value: 'Australia',
        description: 'Australia',
        displayOrder: 5,
        isActive: true,
        metadata: { code: 'AU', dialCode: '+61' },
      },

      // Indian States/Regions
      {
        category: 'region',
        key: 'maharashtra',
        value: 'Maharashtra',
        description: 'State of Maharashtra',
        displayOrder: 1,
        isActive: true,
        metadata: { country: 'india' },
      },
      {
        category: 'region',
        key: 'karnataka',
        value: 'Karnataka',
        description: 'State of Karnataka',
        displayOrder: 2,
        isActive: true,
        metadata: { country: 'india' },
      },
      {
        category: 'region',
        key: 'delhi',
        value: 'Delhi',
        description: 'National Capital Territory of Delhi',
        displayOrder: 3,
        isActive: true,
        metadata: { country: 'india' },
      },
      {
        category: 'region',
        key: 'tamil-nadu',
        value: 'Tamil Nadu',
        description: 'State of Tamil Nadu',
        displayOrder: 4,
        isActive: true,
        metadata: { country: 'india' },
      },
      {
        category: 'region',
        key: 'gujarat',
        value: 'Gujarat',
        description: 'State of Gujarat',
        displayOrder: 5,
        isActive: true,
        metadata: { country: 'india' },
      },
      {
        category: 'region',
        key: 'west-bengal',
        value: 'West Bengal',
        description: 'State of West Bengal',
        displayOrder: 6,
        isActive: true,
        metadata: { country: 'india' },
      },
      {
        category: 'region',
        key: 'rajasthan',
        value: 'Rajasthan',
        description: 'State of Rajasthan',
        displayOrder: 7,
        isActive: true,
        metadata: { country: 'india' },
      },
      {
        category: 'region',
        key: 'uttar-pradesh',
        value: 'Uttar Pradesh',
        description: 'State of Uttar Pradesh',
        displayOrder: 8,
        isActive: true,
        metadata: { country: 'india' },
      },
      {
        category: 'region',
        key: 'andhra-pradesh',
        value: 'Andhra Pradesh',
        description: 'State of Andhra Pradesh',
        displayOrder: 9,
        isActive: true,
        metadata: { country: 'india' },
      },
      {
        category: 'region',
        key: 'telangana',
        value: 'Telangana',
        description: 'State of Telangana',
        displayOrder: 10,
        isActive: true,
        metadata: { country: 'india' },
      },
      {
        category: 'region',
        key: 'kerala',
        value: 'Kerala',
        description: 'State of Kerala',
        displayOrder: 11,
        isActive: true,
        metadata: { country: 'india' },
      },
      {
        category: 'region',
        key: 'punjab',
        value: 'Punjab',
        description: 'State of Punjab',
        displayOrder: 12,
        isActive: true,
        metadata: { country: 'india' },
      },
      {
        category: 'region',
        key: 'haryana',
        value: 'Haryana',
        description: 'State of Haryana',
        displayOrder: 13,
        isActive: true,
        metadata: { country: 'india' },
      },

      // Cities (Major Indian Cities)
      {
        category: 'city',
        key: 'mumbai',
        value: 'Mumbai',
        description: 'Mumbai, Maharashtra',
        displayOrder: 1,
        isActive: true,
        metadata: { state: 'maharashtra', country: 'india' },
      },
      {
        category: 'city',
        key: 'pune',
        value: 'Pune',
        description: 'Pune, Maharashtra',
        displayOrder: 2,
        isActive: true,
        metadata: { state: 'maharashtra', country: 'india' },
      },
      {
        category: 'city',
        key: 'bangalore',
        value: 'Bangalore',
        description: 'Bangalore, Karnataka',
        displayOrder: 3,
        isActive: true,
        metadata: { state: 'karnataka', country: 'india' },
      },
      {
        category: 'city',
        key: 'delhi',
        value: 'Delhi',
        description: 'Delhi, National Capital Territory',
        displayOrder: 4,
        isActive: true,
        metadata: { state: 'delhi', country: 'india' },
      },
      {
        category: 'city',
        key: 'chennai',
        value: 'Chennai',
        description: 'Chennai, Tamil Nadu',
        displayOrder: 5,
        isActive: true,
        metadata: { state: 'tamil-nadu', country: 'india' },
      },
      {
        category: 'city',
        key: 'kolkata',
        value: 'Kolkata',
        description: 'Kolkata, West Bengal',
        displayOrder: 6,
        isActive: true,
        metadata: { state: 'west-bengal', country: 'india' },
      },
      {
        category: 'city',
        key: 'hyderabad',
        value: 'Hyderabad',
        description: 'Hyderabad, Telangana',
        displayOrder: 7,
        isActive: true,
        metadata: { state: 'telangana', country: 'india' },
      },
      {
        category: 'city',
        key: 'ahmedabad',
        value: 'Ahmedabad',
        description: 'Ahmedabad, Gujarat',
        displayOrder: 8,
        isActive: true,
        metadata: { state: 'gujarat', country: 'india' },
      },
      {
        category: 'city',
        key: 'jaipur',
        value: 'Jaipur',
        description: 'Jaipur, Rajasthan',
        displayOrder: 9,
        isActive: true,
        metadata: { state: 'rajasthan', country: 'india' },
      },
      {
        category: 'city',
        key: 'lucknow',
        value: 'Lucknow',
        description: 'Lucknow, Uttar Pradesh',
        displayOrder: 10,
        isActive: true,
        metadata: { state: 'uttar-pradesh', country: 'india' },
      },

      // Centers/Departments
      {
        category: 'center',
        key: 'head-office-mumbai',
        value: 'Head Office - Mumbai',
        description: 'Main headquarters location in Mumbai',
        displayOrder: 1,
        isActive: true,
        metadata: {
          address: 'Bandra Kurla Complex, Bandra East',
          city: 'mumbai',
          state: 'maharashtra',
          zipcode: '400051',
          timing: 'Mon-Fri: 9:00 AM - 6:00 PM, Sat: 9:00 AM - 1:00 PM',
          googleMapLink: 'https://maps.google.com/?q=Bandra+Kurla+Complex+Mumbai',
          phone: '+91-22-26571234',
          email: 'mumbai.ho@helpdesk.gov.in'
        },
      },
      {
        category: 'center',
        key: 'regional-office-delhi',
        value: 'Regional Office - Delhi',
        description: 'Northern region office in Delhi',
        displayOrder: 2,
        isActive: true,
        metadata: {
          address: 'Connaught Place, New Delhi',
          city: 'delhi',
          state: 'delhi',
          zipcode: '110001',
          timing: 'Mon-Fri: 9:30 AM - 6:00 PM',
          googleMapLink: 'https://maps.google.com/?q=Connaught+Place+Delhi',
          phone: '+91-11-23415678',
          email: 'delhi.ro@helpdesk.gov.in'
        },
      },
      {
        category: 'center',
        key: 'regional-office-bangalore',
        value: 'Regional Office - Bangalore',
        description: 'Southern region office in Bangalore',
        displayOrder: 3,
        isActive: true,
        metadata: {
          address: 'MG Road, Bangalore',
          city: 'bangalore',
          state: 'karnataka',
          zipcode: '560001',
          timing: 'Mon-Sat: 9:00 AM - 6:00 PM',
          googleMapLink: 'https://maps.google.com/?q=MG+Road+Bangalore',
          phone: '+91-80-25584567',
          email: 'bangalore.ro@helpdesk.gov.in'
        },
      },
      {
        category: 'center',
        key: 'regional-office-kolkata',
        value: 'Regional Office - Kolkata',
        description: 'Eastern region office in Kolkata',
        displayOrder: 4,
        isActive: true,
        metadata: {
          address: 'Park Street, Kolkata',
          city: 'kolkata',
          state: 'west-bengal',
          zipcode: '700016',
          timing: 'Mon-Fri: 10:00 AM - 6:00 PM',
          googleMapLink: 'https://maps.google.com/?q=Park+Street+Kolkata',
          phone: '+91-33-22891234',
          email: 'kolkata.ro@helpdesk.gov.in'
        },
      },
      {
        category: 'center',
        key: 'branch-office-pune',
        value: 'Branch Office - Pune',
        description: 'Pune branch office',
        displayOrder: 5,
        isActive: true,
        metadata: {
          address: 'Shivaji Nagar, Pune',
          city: 'pune',
          state: 'maharashtra',
          zipcode: '411005',
          timing: 'Mon-Sat: 9:00 AM - 5:00 PM',
          googleMapLink: 'https://maps.google.com/?q=Shivaji+Nagar+Pune',
          phone: '+91-20-25671234',
          email: 'pune.branch@helpdesk.gov.in'
        },
      },
      {
        category: 'center',
        key: 'service-center-chennai',
        value: 'Service Center - Chennai',
        description: 'Customer service center in Chennai',
        displayOrder: 6,
        isActive: true,
        metadata: {
          address: 'Anna Salai, Chennai',
          city: 'chennai',
          state: 'tamil-nadu',
          zipcode: '600002',
          timing: 'Mon-Sat: 9:00 AM - 6:00 PM',
          googleMapLink: 'https://maps.google.com/?q=Anna+Salai+Chennai',
          phone: '+91-44-28521234',
          email: 'chennai.service@helpdesk.gov.in'
        },
      },
      {
        category: 'center',
        key: 'service-center-hyderabad',
        value: 'Service Center - Hyderabad',
        description: 'Customer service center in Hyderabad',
        displayOrder: 7,
        isActive: true,
        metadata: {
          address: 'Banjara Hills, Hyderabad',
          city: 'hyderabad',
          state: 'telangana',
          zipcode: '500034',
          timing: 'Mon-Fri: 9:00 AM - 7:00 PM, Sat: 10:00 AM - 2:00 PM',
          googleMapLink: 'https://maps.google.com/?q=Banjara+Hills+Hyderabad',
          phone: '+91-40-23451234',
          email: 'hyderabad.service@helpdesk.gov.in'
        },
      },

      // Organization Master (Sample Organizations)
      {
        category: 'organization',
        key: 'sac-helpdesk',
        value: 'SAC Helpdesk',
        description: 'State Administrative Council Helpdesk',
        displayOrder: 1,
        isActive: true,
        metadata: { type: 'government', website: 'https://sac.gov.in' },
      },
      {
        category: 'organization',
        key: 'niti-aayog',
        value: 'NITI Aayog',
        description: 'National Institution for Transforming India',
        displayOrder: 2,
        isActive: true,
        metadata: { type: 'government', website: 'https://niti.gov.in' },
      },
      {
        category: 'organization',
        key: 'ministry-electronics-it',
        value: 'Ministry of Electronics & IT',
        description: 'MeitY - Government of India',
        displayOrder: 3,
        isActive: true,
        metadata: { type: 'government', website: 'https://meity.gov.in' },
      },
      {
        category: 'organization',
        key: 'digital-india',
        value: 'Digital India',
        description: 'Digital India Programme',
        displayOrder: 4,
        isActive: true,
        metadata: { type: 'government', website: 'https://digitalindia.gov.in' },
      },

      // Currencies
      {
        category: 'currency',
        key: 'inr',
        value: 'Indian Rupee (₹)',
        description: 'Indian Rupee',
        displayOrder: 1,
        isActive: true,
        metadata: { code: 'INR', symbol: '₹' },
      },
      {
        category: 'currency',
        key: 'usd',
        value: 'US Dollar ($)',
        description: 'United States Dollar',
        displayOrder: 2,
        isActive: true,
        metadata: { code: 'USD', symbol: '$' },
      },
      {
        category: 'currency',
        key: 'eur',
        value: 'Euro (€)',
        description: 'Euro',
        displayOrder: 3,
        isActive: true,
        metadata: { code: 'EUR', symbol: '€' },
      },
      {
        category: 'currency',
        key: 'gbp',
        value: 'British Pound (£)',
        description: 'British Pound Sterling',
        displayOrder: 4,
        isActive: true,
        metadata: { code: 'GBP', symbol: '£' },
      },

      // Timezones
      {
        category: 'timezone',
        key: 'ist',
        value: 'Asia/Kolkata (IST)',
        description: 'Indian Standard Time',
        displayOrder: 1,
        isActive: true,
        metadata: { offset: '+05:30' },
      },
      {
        category: 'timezone',
        key: 'utc',
        value: 'UTC',
        description: 'Coordinated Universal Time',
        displayOrder: 2,
        isActive: true,
        metadata: { offset: '+00:00' },
      },
      {
        category: 'timezone',
        key: 'est',
        value: 'America/New_York (EST)',
        description: 'Eastern Standard Time',
        displayOrder: 3,
        isActive: true,
        metadata: { offset: '-05:00' },
      },
      {
        category: 'timezone',
        key: 'pst',
        value: 'America/Los_Angeles (PST)',
        description: 'Pacific Standard Time',
        displayOrder: 4,
        isActive: true,
        metadata: { offset: '-08:00' },
      },
      {
        category: 'timezone',
        key: 'gmt',
        value: 'Europe/London (GMT)',
        description: 'Greenwich Mean Time',
        displayOrder: 5,
        isActive: true,
        metadata: { offset: '+00:00' },
      },

      // Date Formats
      {
        category: 'dateFormat',
        key: 'dd-mm-yyyy',
        value: 'DD/MM/YYYY',
        description: 'Day/Month/Year (Indian format)',
        displayOrder: 1,
        isActive: true,
      },
      {
        category: 'dateFormat',
        key: 'mm-dd-yyyy',
        value: 'MM/DD/YYYY',
        description: 'Month/Day/Year (US format)',
        displayOrder: 2,
        isActive: true,
      },
      {
        category: 'dateFormat',
        key: 'yyyy-mm-dd',
        value: 'YYYY-MM-DD',
        description: 'Year-Month-Day (ISO format)',
        displayOrder: 3,
        isActive: true,
      },

      // Languages
      {
        category: 'language',
        key: 'en',
        value: 'English',
        description: 'English language',
        displayOrder: 1,
        isActive: true,
        metadata: { code: 'en', nativeName: 'English' },
      },
      {
        category: 'language',
        key: 'mr',
        value: 'Marathi',
        description: 'Marathi language',
        displayOrder: 2,
        isActive: true,
        metadata: { code: 'mr', nativeName: 'मराठी' },
      },
      {
        category: 'language',
        key: 'hi',
        value: 'Hindi',
        description: 'Hindi language',
        displayOrder: 3,
        isActive: true,
        metadata: { code: 'hi', nativeName: 'हिन्दी' },
      },
    ];

    // Insert all master data items
    await MasterData.insertMany(masterDataItems);

    console.log('✅ Master data seeded successfully');
    console.log(`📊 Total items: ${masterDataItems.length}`);
    console.log('📋 Categories:', [
      'organizationType',
      'industry',
      'country',
      'region',
      'city',
      'center',
      'organization',
      'currency',
      'timezone',
      'dateFormat',
      'language',
    ]);
  } catch (error: any) {
    console.error('❌ Error seeding master data:', error.message);
    throw error;
  }
};
